export const fleet = [
  {
    id: 1,
    name: "Swift Dzire",
    seats: "4+1",
    type: "Sedan",
    image: "/cars/swift-dzire.svg",
    features: ["AC", "Airport", "Outstation"],
  },
  {
    id: 2,
    name: "Toyota Innova",
    seats: "6+1",
    type: "SUV",
    image: "/cars/innova.svg",
    features: ["Premium", "Family", "Outstation"],
  },
  {
    id: 3,
    name: "Maruti Ertiga",
    seats: "6+1",
    type: "MPV",
    image: "/cars/ertiga.svg",
    features: ["Family", "Comfort", "AC"],
  },
  {
    id: 4,
    name: "Tata Indica",
    seats: "4+1",
    type: "Hatchback",
    image: "/cars/indica.svg",
    features: ["Budget", "Local", "AC"],
  },
  {
    id: 5,
    name: "Maruti Eeco",
    seats: "5+1",
    type: "Van",
    image: "/cars/eeco.svg",
    features: ["Group", "Local", "Airport"],
  },
  {
    id: 6,
    name: "Tempo Traveller",
    seats: "12–17",
    type: "Traveller",
    image: "/cars/tempo-traveller.svg",
    features: ["Group", "Outstation", "Tour"],
  },
];