export const fleet = [
  {
    name: "Swift Dzire",
    image: "/cars/swift-dzire.svg",
    seats: "4+1",
    luggage: "2 Bags",
    type: "Sedan",
    ac: true,
    fuel: "Petrol / CNG",
    bestFor: "Airport, Local, Business",
    description: "Comfortable for airport transfers, local travel and business trips.",
  },
  {
    name: "Toyota Innova",
    image: "/cars/innova.svg",
    seats: "6+1",
    luggage: "4 Bags",
    type: "SUV",
    ac: true,
    fuel: "Diesel",
    bestFor: "Family, Outstation",
    description: "Perfect for family trips and long-distance journeys.",
  },
  {
    name: "Maruti Ertiga",
    image: "/cars/ertiga.svg",
    seats: "6+1",
    luggage: "3 Bags",
    type: "MPV",
    ac: true,
    fuel: "Petrol / CNG",
    bestFor: "Airport, Family",
    description: "Spacious and economical for family travel.",
  },
  {
    name: "Tata Indica",
    image: "/cars/indica.svg",
    seats: "4+1",
    luggage: "2 Bags",
    type: "Hatchback",
    ac: true,
    fuel: "Petrol / CNG",
    bestFor: "Budget Travel",
    description: "Budget-friendly option for city rides.",
  },
  {
    name: "Maruti Eeco",
    image: "/cars/eeco.svg",
    seats: "5+1",
    luggage: "3 Bags",
    type: "Van",
    ac: true,
    fuel: "Petrol / CNG",
    bestFor: "Budget Travel",
    description: "Suitable for small groups and extra luggage.",
  },
  {
    name: "Tempo Traveller",
    image: "/cars/tempo-traveller.svg",
    seats: "12-17",
    luggage: "Large",
    type: "Traveller",
    ac: true,
    fuel: "Diesel",
    bestFor: "Groups, Tours, Weddings",
    description: "Best for tours, weddings and group travel.",
  },
];